name: Test

on: [push]

jobs:
  test:
    # where to launch
    runs-on: ubuntu-latest
    # what to do
    steps:
      # download repository
      - uses: actions/checkout@v3
      # configure java
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      # run tests
      - run: ./gradlew clean test